### PR TITLE
catch 403 responses

### PR DESCRIPTION
**Pull request by Hyperkid123**
cc @john-dupuy There is not a single unit test, unfortunately. And I have basically changed every API call. Can you do a test run? Please. There will be more tests, I will make sure of it. In fact we need to do a major refactoring because there is a lot of strange stuff.

### CODE REVIEW

**Comment by john-dupuy** [comment]
@Hyperkid123 I've been playing with this locally this morning. The main issue I see can be reproduced by:
1) Navigating to internal bundle
2) Viewing the second page of access requests in the table
3) Filtering the table on some value that only has one result (e.g. approved)

This seems to mess up the pagination, screenshot is attached:
Screenshot from 2021-11-23 07-50-29


The other thing I noticed is that when I try to view the account of the approver as the requester, the page just refreshes and I'm kicked back to the account of the requester. Not sure if this is a local dev thing or something caused by these changes.

**Comment by john-dupuy** [comment]
About the first issue 
> This seems to mess up the pagination, screenshot is attached:
I can reproduce the same issue in stage-beta, though the pagination values are correct. Here, just the row isn't displayed. 

Screenshot from 2021-11-23 08-02-40

**Comment by john-dupuy** [comment]
@Hyperkid123 https://issues.redhat.com/browse/RHCLOUD-17072

> The other thing I noticed is that when I try to view the account of the approver as the requester, the page just refreshes and I'm kicked back to the account of the requester. Not sure if this is a local dev thing or something caused by these changes.

Do you know if this is a result of running in the dev env?

**Comment by Hyperkid123** [comment]
> Do you know if this is a result of running in the dev env?

Chrome is responsible for kicking you out if your request has been terminated. So I would say yes.

**Comment by john-dupuy** [comment]
Alright, in that case I'll have to test the catching of the 403 response post-merge.

**Review by john-dupuy — APPROVED** [review]

**Pull request merged**
